import React from 'react';
import Head from 'next/head';

import { Login } from '@spotify-clone/shared';

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>@spotify-clone | yasinatesim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
    </div>
  );
};

export default Home;
