import React from 'react';
import Head from 'next/head';

import { Login } from '@spotify-clone/shared';

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
    </div>
  );
}

export default Home;
