import React from 'react';
import Head from 'next/head';

const Collection: React.FC = () => {
  return (
    <>
      <Head>
        <title>Koleksiyonlar | yasinatesim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      burası collection
    </>
  );
};

export default Collection;
