import React from 'react';
import Head from 'next/head';

// import { Login } from '@spotify-clone/shared';

function Home() {
  return (
    <>
      <Head>
        <title>@spotify-clone | yasinatesim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      burası collection
      {/* <Login /> */}
    </>
  );
}

export default Home;
