import React from 'react';
import Head from 'next/head';
import Sidebar from '@spotify-clone/desktop/src/universal/containers/sidebar';
// import Headerr from '@spotify-clone/desktop/src/universal/containers/hader';

// import { Login } from '@spotify-clone/shared';

function Home() {
  return (
    <>
      <Head>
        <title>@spotify-clone | yasinatesim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="wrapper">
        <Sidebar />
        {/* <Content/> */}
      </div>
      {/* <Footer/> */}
      {/* <Login /> */}
    </>
  );
}

export default Home;
