import React from 'react';
import Head from 'next/head';

const Search: React.FC = () => {
  return (
    <>
      <Head>
        <title>Search | yasinatesim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      burası search
    </>
  );
};

export default Search;
